version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mule_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mule
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: mule_app
    depends_on:
      - db
    environment:
      REDSHIFT_PASSWORD: secret
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    command: ["bash", "-c", "sleep 5 && python core/engine.py && uvicorn api.server:app --host 0.0.0.0 --port 8000"]

volumes:
  pgdata:
